# Generated by Django 5.2.6 on 2025-10-07 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0003_alter_organizationinvitation_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PosterGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                ("negative_prompt", models.TextField(blank=True, null=True)),
                ("design_metadata", models.JSONField(blank=True, default=dict)),
                ("width", models.IntegerField(default=1024)),
                ("height", models.IntegerField(default=1024)),
                ("num_images", models.IntegerField(default=1)),
                ("guidance_scale", models.FloatField(default=7.5)),
                ("num_inference_steps", models.IntegerField(default=20)),
                ("generated_images", models.JSONField(blank=True, default=list)),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poster_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Poster Generation Job",
                "verbose_name_plural": "Poster Generation Jobs",
                "db_table": "poster_generation_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PosterGenerationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_satisfaction_rating",
                    models.IntegerField(blank=True, null=True),
                ),
                ("user_feedback", models.TextField(blank=True)),
                ("regeneration_count", models.IntegerField(default=0)),
                ("final_selection", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poster_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="poster_generation.postergenerationjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poster Generation History",
                "verbose_name_plural": "Poster Generation Histories",
                "db_table": "poster_generation_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PosterTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("textile", "Textile Design"),
                            ("fashion", "Fashion"),
                            ("festival", "Festival"),
                            ("business", "Business"),
                            ("creative", "Creative"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prompt_template", models.TextField()),
                ("negative_prompt_template", models.TextField(blank=True)),
                ("default_parameters", models.JSONField(blank=True, default=dict)),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="poster_templates/previews/"
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("is_public", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_poster_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poster Template",
                "verbose_name_plural": "Poster Templates",
                "db_table": "poster_templates",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="postergenerationjob",
            index=models.Index(
                fields=["organization", "status"], name="poster_gene_organiz_4c8012_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postergenerationjob",
            index=models.Index(
                fields=["user", "status"], name="poster_gene_user_id_eb2167_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postergenerationjob",
            index=models.Index(
                fields=["created_at"], name="poster_gene_created_cc4673_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postertemplate",
            index=models.Index(
                fields=["organization", "category"],
                name="poster_temp_organiz_661910_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postertemplate",
            index=models.Index(
                fields=["is_public", "is_active"], name="poster_temp_is_publ_374851_idx"
            ),
        ),
    ]
