# Generated by Django 5.2.6 on 2025-10-07 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("designs", "0001_initial"),
        ("organizations", "0003_alter_organizationinvitation_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignCollaboration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("allow_edit", models.BooleanField(default=True)),
                ("allow_comments", models.BooleanField(default=True)),
                ("auto_save", models.BooleanField(default=True)),
                ("session_data", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations",
                        to="designs.design",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_collaborations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collaborations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Collaboration",
                "verbose_name_plural": "Design Collaborations",
                "db_table": "design_collaborations",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="DesignComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="designs.design",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="collaboration.designcomment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Comment",
                "verbose_name_plural": "Design Comments",
                "db_table": "design_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("comment", "Comment"),
                            ("edit", "Edit"),
                            ("admin", "Admin"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "share_token",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("allow_download", models.BooleanField(default=False)),
                ("allow_comments", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="designs.design",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_designs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Share",
                "verbose_name_plural": "Design Shares",
                "db_table": "design_shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("version_data", models.JSONField(blank=True, default=dict)),
                ("changes_summary", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="designs/versions/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collaboration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="collaboration.designcollaboration",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="designs.design",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Version",
                "verbose_name_plural": "Design Versions",
                "db_table": "design_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="DesignActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("edit", "Edit"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("export", "Export"),
                            ("version", "Version Created"),
                            ("collaboration_start", "Collaboration Started"),
                            ("collaboration_end", "Collaboration Ended"),
                        ],
                        max_length=30,
                    ),
                ),
                ("activity_data", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="designs.design",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_collaboration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collaboration.designcollaboration",
                    ),
                ),
                (
                    "related_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collaboration.designcomment",
                    ),
                ),
                (
                    "related_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collaboration.designversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Activity",
                "verbose_name_plural": "Design Activities",
                "db_table": "design_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="designcollaboration",
            index=models.Index(
                fields=["organization", "design"], name="design_coll_organiz_65e72f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designcollaboration",
            index=models.Index(
                fields=["initiator"], name="design_coll_initiat_94e8db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designcollaboration",
            index=models.Index(fields=["status"], name="design_coll_status_fb5876_idx"),
        ),
        migrations.AddIndex(
            model_name="designcollaboration",
            index=models.Index(
                fields=["last_activity"], name="design_coll_last_ac_6de028_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designcomment",
            index=models.Index(
                fields=["organization", "design"], name="design_comm_organiz_9a2f32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designcomment",
            index=models.Index(
                fields=["author"], name="design_comm_author__fb4bce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designcomment",
            index=models.Index(
                fields=["parent_comment"], name="design_comm_parent__a983bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designshare",
            index=models.Index(
                fields=["organization", "design"], name="design_shar_organiz_4795d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designshare",
            index=models.Index(
                fields=["shared_by"], name="design_shar_shared__3b3915_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designshare",
            index=models.Index(
                fields=["shared_with"], name="design_shar_shared__0922b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designshare",
            index=models.Index(
                fields=["share_token"], name="design_shar_share_t_3881fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designshare",
            index=models.Index(
                fields=["status", "expires_at"], name="design_shar_status_0f66ee_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="designshare",
            unique_together={("design", "shared_with", "organization")},
        ),
        migrations.AddIndex(
            model_name="designversion",
            index=models.Index(
                fields=["organization", "design"], name="design_vers_organiz_2f05f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designversion",
            index=models.Index(
                fields=["created_by"], name="design_vers_created_59871e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designversion",
            index=models.Index(
                fields=["collaboration"], name="design_vers_collabo_02d575_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="designversion",
            unique_together={("design", "version_number", "organization")},
        ),
        migrations.AddIndex(
            model_name="designactivity",
            index=models.Index(
                fields=["organization", "design"], name="design_acti_organiz_8612f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designactivity",
            index=models.Index(fields=["user"], name="design_acti_user_id_606947_idx"),
        ),
        migrations.AddIndex(
            model_name="designactivity",
            index=models.Index(
                fields=["activity_type"], name="design_acti_activit_c9d28c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designactivity",
            index=models.Index(
                fields=["created_at"], name="design_acti_created_32b09b_idx"
            ),
        ),
    ]
