#!/usr/bin/env python3
"""
Direct MySQL Database Setup Script for Frameio
This script sets up MySQL database without requiring mysql command line tools
"""

import os
import sys
import subprocess
from getpass import getpass

def print_header(message):
    """Print a formatted header"""
    print("\n" + "=" * 70)
    print(f"  {message}")
    print("=" * 70)

def create_database(host, port, user, password, db_name):
    """Create the MySQL database"""
    try:
        # Try mysql-connector-python first
        try:
            import mysql.connector
            from mysql.connector import Error
            
            connection = mysql.connector.connect(
                host=host,
                port=port,
                user=user,
                password=password
            )
            
            if connection.is_connected():
                cursor = connection.cursor()
                cursor.execute(
                    f"CREATE DATABASE IF NOT EXISTS {db_name} "
                    f"CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
                )
                print(f"✓ Database '{db_name}' created successfully")
                
                cursor.execute(f"USE {db_name}")
                cursor.execute(
                    "SELECT DATABASE() as db, "
                    "@@character_set_database as charset, "
                    "@@collation_database as collation"
                )
                result = cursor.fetchone()
                print(f"  - Database: {result[0]}")
                print(f"  - Character Set: {result[1]}")
                print(f"  - Collation: {result[2]}")
                
                cursor.close()
                connection.close()
                return True
        except ImportError:
            # Fall back to MySQLdb (mysqlclient)
            import MySQLdb
            
            connection = MySQLdb.connect(
                host=host,
                port=port,
                user=user,
                passwd=password
            )
            
            cursor = connection.cursor()
            cursor.execute(
                f"CREATE DATABASE IF NOT EXISTS {db_name} "
                f"CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
            )
            print(f"✓ Database '{db_name}' created successfully")
            
            cursor.execute(f"USE {db_name}")
            cursor.execute(
                "SELECT DATABASE() as db, "
                "@@character_set_database as charset, "
                "@@collation_database as collation"
            )
            result = cursor.fetchone()
            print(f"  - Database: {result[0]}")
            print(f"  - Character Set: {result[1]}")
            print(f"  - Collation: {result[2]}")
            
            cursor.close()
            connection.close()
            return True
            
    except Exception as e:
        print(f"✗ Error creating database: {e}")
        print(f"  Error type: {type(e).__name__}")
        return False

def create_env_file(db_name, db_user, db_password, db_host, db_port):
    """Create or update .env file with database credentials"""
    env_path = os.path.join('backend', '.env')
    template_path = 'env.template'
    
    # Read template if exists
    env_content = ""
    if os.path.exists(template_path):
        with open(template_path, 'r') as f:
            env_content = f.read()
    
    # Database configuration
    db_config = f"""# MySQL Database Configuration (Auto-generated by setup_mysql_direct.py)
DB_NAME={db_name}
DB_USER={db_user}
DB_PASSWORD={db_password}
DB_HOST={db_host}
DB_PORT={db_port}
USE_SQLITE_FALLBACK=False
"""
    
    # If .env exists, update it; otherwise create new
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            existing_content = f.read()
        
        # Remove old DB configuration if exists
        lines = []
        skip_db = False
        for line in existing_content.split('\n'):
            if line.startswith('# MySQL Database Configuration') or line.startswith('# DATABASE CONFIGURATION'):
                skip_db = True
            elif skip_db and (line.startswith('DB_') or line.startswith('USE_SQLITE_FALLBACK')):
                continue
            elif skip_db and line.strip() == '':
                continue
            elif skip_db and not (line.startswith('DB_') or line.startswith('USE_SQLITE_FALLBACK')):
                skip_db = False
                lines.append(db_config.strip())
                lines.append(line)
            else:
                lines.append(line)
        
        if skip_db:
            lines.append(db_config.strip())
        
        env_content = '\n'.join(lines)
    else:
        # Create new .env from template or with minimal config
        if env_content:
            # Insert DB config after DATABASE CONFIGURATION section
            if '# DATABASE CONFIGURATION' in env_content:
                env_content = env_content.replace(
                    '# DATABASE CONFIGURATION',
                    '# DATABASE CONFIGURATION\n' + db_config.strip()
                )
            else:
                env_content = db_config + env_content
        else:
            env_content = db_config
    
    # Ensure backend directory exists
    os.makedirs('backend', exist_ok=True)
    
    # Write .env file
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"✓ Environment file updated: {env_path}")

def run_migrations():
    """Run Django migrations"""
    try:
        backend_path = 'backend'
        if not os.path.exists(backend_path):
            print("⚠ Backend directory not found, skipping migrations")
            return
        
        print("\nRunning Django migrations...")
        result = subprocess.run(
            [sys.executable, 'manage.py', 'migrate'],
            cwd=backend_path,
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            print("✓ Migrations completed successfully")
            if result.stdout:
                print(result.stdout)
        else:
            print("⚠ Migrations had issues")
            if result.stderr:
                print(result.stderr)
            if result.stdout:
                print(result.stdout)
            
    except Exception as e:
        print(f"⚠ Error running migrations: {e}")

def main():
    """Main setup function"""
    print_header("Frameio MySQL Database Setup")
    
    print("\nEnter MySQL connection details:")
    print("(Press Enter to use defaults)")
    db_host = input("MySQL Host [localhost]: ").strip() or "localhost"
    db_port = input("MySQL Port [3306]: ").strip() or "3306"
    db_user = input("MySQL User [root]: ").strip() or "root"
    db_password = getpass("MySQL Password: ")
    if not db_password:
        print("⚠ Warning: Empty password. Make sure this is correct.")
    db_name = input("Database Name [frameio_db]: ").strip() or "frameio_db"
    
    print_header("Creating Database")
    
    # Create database
    if create_database(db_host, int(db_port), db_user, db_password, db_name):
        print_header("Updating Environment Configuration")
        create_env_file(db_name, db_user, db_password, db_host, db_port)
        
        print_header("Running Migrations")
        run_migrations()
        
        print_header("Setup Complete!")
        print("\n✓ Your MySQL database is ready to use!")
        print("\nNext steps:")
        print("1. Review your backend/.env file")
        print("2. Start the backend: cd backend && python manage.py runserver")
        print("3. Start the frontend: cd frontend && npm run dev")
    else:
        print("\n✗ Database setup failed.")
        print("\nTroubleshooting:")
        print("1. Make sure MySQL service is running")
        print("2. Check your MySQL username and password")
        print("3. Verify MySQL is listening on the correct port")
        print("4. Try starting MySQL service: net start MySQL80 (or check Services)")
        sys.exit(1)

if __name__ == "__main__":
    main()

