#!/usr/bin/env python3
"""
MySQL Database Setup Script for Frameio
This script helps set up the MySQL database for the Frameio application
"""

import os
import sys
import subprocess
from getpass import getpass

def print_header(message):
    """Print a formatted header"""
    print("\n" + "=" * 70)
    print(f"  {message}")
    print("=" * 70)

def check_mysql_installed():
    """Check if MySQL is installed and accessible"""
    try:
        result = subprocess.run(
            ['mysql', '--version'],
            capture_output=True,
            text=True,
            check=True
        )
        print(f"✓ MySQL found: {result.stdout.strip()}")
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("✗ MySQL is not installed or not in PATH")
        return False

def create_database(host, port, user, password, db_name):
    """Create the MySQL database"""
    try:
        import mysql.connector
        from mysql.connector import Error
        
        # Connect to MySQL server
        connection = mysql.connector.connect(
            host=host,
            port=port,
            user=user,
            password=password
        )
        
        if connection.is_connected():
            cursor = connection.cursor()
            
            # Create database
            cursor.execute(
                f"CREATE DATABASE IF NOT EXISTS {db_name} "
                f"CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
            )
            print(f"✓ Database '{db_name}' created successfully")
            
            # Show database info
            cursor.execute(f"USE {db_name}")
            cursor.execute(
                "SELECT DATABASE() as db, "
                "@@character_set_database as charset, "
                "@@collation_database as collation"
            )
            result = cursor.fetchone()
            print(f"  - Database: {result[0]}")
            print(f"  - Character Set: {result[1]}")
            print(f"  - Collation: {result[2]}")
            
            cursor.close()
            connection.close()
            return True
            
    except Error as e:
        print(f"✗ Error creating database: {e}")
        return False
    except ImportError:
        print("✗ mysql-connector-python not installed")
        print("  Install it with: pip install mysql-connector-python")
        return False

def create_env_file(db_name, db_user, db_password, db_host, db_port):
    """Create or update .env file with database credentials"""
    env_path = os.path.join(os.path.dirname(__file__), '.env')
    template_path = os.path.join(os.path.dirname(__file__), 'env.template')
    
    # Read template if exists
    if os.path.exists(template_path):
        with open(template_path, 'r') as f:
            env_content = f.read()
    else:
        env_content = ""
    
    # Update database settings
    db_config = f"""
# MySQL Database Configuration (Auto-generated by setup_mysql.py)
DB_NAME={db_name}
DB_USER={db_user}
DB_PASSWORD={db_password}
DB_HOST={db_host}
DB_PORT={db_port}
"""
    
    # If .env exists, update it; otherwise create new
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            existing_content = f.read()
        
        # Remove old DB configuration if exists
        lines = []
        skip_db = False
        for line in existing_content.split('\n'):
            if line.startswith('# MySQL Database Configuration'):
                skip_db = True
            elif skip_db and line.startswith('DB_'):
                continue
            elif skip_db and not line.startswith('DB_'):
                skip_db = False
                lines.append(db_config.strip())
                lines.append(line)
            else:
                lines.append(line)
        
        if not skip_db:
            lines.append(db_config.strip())
        
        env_content = '\n'.join(lines)
    else:
        env_content = db_config
    
    # Write .env file
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"✓ Environment file updated: {env_path}")

def run_migrations():
    """Run Django migrations"""
    try:
        backend_path = os.path.join(os.path.dirname(__file__), 'backend')
        if not os.path.exists(backend_path):
            print("⚠ Backend directory not found, skipping migrations")
            return
        
        print("\nRunning Django migrations...")
        result = subprocess.run(
            [sys.executable, 'manage.py', 'migrate'],
            cwd=backend_path,
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            print("✓ Migrations completed successfully")
            print(result.stdout)
        else:
            print("⚠ Migrations failed")
            print(result.stderr)
            
    except Exception as e:
        print(f"⚠ Error running migrations: {e}")

def main():
    """Main setup function"""
    print_header("Frameio MySQL Database Setup")
    
    # Check if MySQL is installed
    if not check_mysql_installed():
        print("\nPlease install MySQL 8.0+ and try again.")
        print("Visit: https://dev.mysql.com/downloads/")
        sys.exit(1)
    
    # Get database configuration
    print("\nEnter MySQL connection details:")
    db_host = input("MySQL Host [localhost]: ").strip() or "localhost"
    db_port = input("MySQL Port [3306]: ").strip() or "3306"
    db_user = input("MySQL User [root]: ").strip() or "root"
    db_password = getpass("MySQL Password: ")
    db_name = input("Database Name [frameio_db]: ").strip() or "frameio_db"
    
    print_header("Creating Database")
    
    # Create database
    if create_database(db_host, db_port, db_user, db_password, db_name):
        print_header("Updating Environment Configuration")
        create_env_file(db_name, db_user, db_password, db_host, db_port)
        
        print_header("Running Migrations")
        run_migrations()
        
        print_header("Setup Complete!")
        print("\n✓ Your MySQL database is ready to use!")
        print("\nNext steps:")
        print("1. Review your .env file")
        print("2. Start the backend: cd backend && python manage.py runserver")
        print("3. Start the frontend: cd frontend && npm run dev")
    else:
        print("\n✗ Database setup failed. Please check your MySQL connection.")
        sys.exit(1)

if __name__ == "__main__":
    main()

