"""
Usage Limits Utility
Functions to check and enforce free usage limits for posters and brand kits
"""
from datetime import datetime, timedelta
from calendar import monthrange
from typing import Dict, Optional, Tuple
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.db.models import Q

User = get_user_model()

# Free tier limits
FREE_POSTER_LIMIT = 3
FREE_BRAND_KIT_LIMIT = 3


def get_current_month_range() -> Tuple[datetime, datetime]:
    """
    Get the start and end datetime of the current calendar month
    
    Returns:
        Tuple of (start_of_month, end_of_month) datetime objects
    """
    now = timezone.now()
    # Use timezone-aware datetime
    start_of_month = timezone.make_aware(
        datetime(now.year, now.month, 1, 0, 0, 0, 0)
    ) if timezone.is_naive(datetime(now.year, now.month, 1)) else datetime(now.year, now.month, 1, 0, 0, 0, 0, tzinfo=now.tzinfo)
    
    # Get last day of current month
    last_day = monthrange(now.year, now.month)[1]
    end_of_month = timezone.make_aware(
        datetime(now.year, now.month, last_day, 23, 59, 59, 999999)
    ) if timezone.is_naive(datetime(now.year, now.month, last_day, 23, 59, 59, 999999)) else datetime(now.year, now.month, last_day, 23, 59, 59, 999999, tzinfo=now.tzinfo)
    
    return start_of_month, end_of_month


def get_next_month_start() -> datetime:
    """
    Get the start datetime of the next calendar month (when limits reset)
    
    Returns:
        Datetime object representing the start of next month
    """
    now = timezone.now()
    if now.month == 12:
        next_month = now.replace(year=now.year + 1, month=1, day=1, hour=0, minute=0, second=0, microsecond=0)
    else:
        next_month = now.replace(month=now.month + 1, day=1, hour=0, minute=0, second=0, microsecond=0)
    return next_month


def count_user_posters(user: Optional[User]) -> int:
    """
    Count the number of posters generated by a user in the current month
    
    Args:
        user: User object or None
        
    Returns:
        Number of posters generated this month (0 if user is None)
    """
    if not user:
        return 0
    
    try:
        from ..models import GeneratedPoster
        start_of_month, end_of_month = get_current_month_range()
        
        count = GeneratedPoster.objects.filter(
            user=user,
            created_at__gte=start_of_month,
            created_at__lte=end_of_month
        ).count()
        
        return count
    except Exception:
        # If there's any error (e.g., model not found), return 0
        return 0


def count_user_brand_kits(user: Optional[User]) -> int:
    """
    Count the number of brand kits generated by a user in the current month
    
    Args:
        user: User object or None
        
    Returns:
        Number of brand kits generated this month (0 if user is None)
    """
    if not user:
        return 0
    
    try:
        from ..models import GeneratedBrandingKit
        import logging
        logger = logging.getLogger(__name__)
        
        start_of_month, end_of_month = get_current_month_range()
        
        count = GeneratedBrandingKit.objects.filter(
            user=user,
            created_at__gte=start_of_month,
            created_at__lte=end_of_month
        ).count()
        
        logger.info(f"User {user.id} ({user.email if hasattr(user, 'email') else 'N/A'}) has {count} brand kits this month (from {start_of_month.date()} to {end_of_month.date()})")
        
        return count
    except Exception as e:
        # If there's any error (e.g., model not found), return 0
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Error counting brand kits for user: {e}")
        return 0


def check_poster_limit(user: Optional[User]) -> Tuple[bool, Dict]:
    """
    Check if user has reached the free poster limit
    
    Args:
        user: User object or None
        
    Returns:
        Tuple of (can_generate: bool, error_info: dict)
        If can_generate is False, error_info contains error details
    """
    # If user is None, block generation (unauthenticated users)
    if not user:
        next_reset = get_next_month_start()
        return False, {
            "error": f"Please sign in to generate posters. Free accounts can generate {FREE_POSTER_LIMIT} posters per month.",
            "limit_type": "posters",
            "current_count": 0,
            "limit": FREE_POSTER_LIMIT,
            "reset_date": next_reset.strftime("%Y-%m-%d")
        }
    
    current_count = count_user_posters(user)
    
    # Allow generation if current count is less than limit (so they can generate exactly LIMIT times)
    if current_count >= FREE_POSTER_LIMIT:
        next_reset = get_next_month_start()
        return False, {
            "error": f"You have reached your monthly free limit of {FREE_POSTER_LIMIT} posters. Please upgrade or wait until next month.",
            "limit_type": "posters",
            "current_count": current_count,
            "limit": FREE_POSTER_LIMIT,
            "reset_date": next_reset.strftime("%Y-%m-%d")
        }
    
    return True, {}


def check_brand_kit_limit(user: Optional[User]) -> Tuple[bool, Dict]:
    """
    Check if user has reached the free brand kit limit
    
    Args:
        user: User object or None
        
    Returns:
        Tuple of (can_generate: bool, error_info: dict)
        If can_generate is False, error_info contains error details
    """
    # If user is None, block generation (unauthenticated users)
    if not user:
        next_reset = get_next_month_start()
        return False, {
            "error": f"Please sign in to generate brand kits. Free accounts can generate {FREE_BRAND_KIT_LIMIT} brand kits per month.",
            "limit_type": "brand_kits",
            "current_count": 0,
            "limit": FREE_BRAND_KIT_LIMIT,
            "reset_date": next_reset.strftime("%Y-%m-%d")
        }
    
    current_count = count_user_brand_kits(user)
    
    # Log the count for debugging
    import logging
    logger = logging.getLogger(__name__)
    logger.info(f"Limit check for user {user.id} ({user.email if hasattr(user, 'email') else 'N/A'}): current_count={current_count}, limit={FREE_BRAND_KIT_LIMIT}, can_generate={current_count < FREE_BRAND_KIT_LIMIT}")
    
    # Allow generation if current count is less than limit (so they can generate exactly LIMIT times)
    # If count is 0, 1, or 2, allow (can generate up to 3rd)
    # If count is 3 or more, block
    # Example: count=0 → allow (can generate 1st), count=1 → allow (can generate 2nd), count=2 → allow (can generate 3rd), count=3 → block
    if current_count >= FREE_BRAND_KIT_LIMIT:
        next_reset = get_next_month_start()
        return False, {
            "error": f"You have reached your monthly free limit of {FREE_BRAND_KIT_LIMIT} brand kits. Please upgrade or wait until next month.",
            "limit_type": "brand_kits",
            "current_count": current_count,
            "limit": FREE_BRAND_KIT_LIMIT,
            "reset_date": next_reset.strftime("%Y-%m-%d")
        }
    
    return True, {}

