# Generated by Django 5.2.5 on 2025-10-03 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0003_alter_organizationinvitation_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "design_type",
                    models.CharField(
                        choices=[
                            ("poster", "Poster"),
                            ("banner", "Banner"),
                            ("flyer", "Flyer"),
                            ("business_card", "Business Card"),
                            ("logo", "Logo"),
                            ("other", "Other"),
                        ],
                        default="poster",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="designs/images/"
                    ),
                ),
                ("ai_prompt", models.TextField(blank=True, null=True)),
                ("ai_generated", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_designs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design",
                "verbose_name_plural": "Designs",
                "db_table": "designs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignCatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_catalogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Catalog",
                "verbose_name_plural": "Design Catalogs",
                "db_table": "design_catalogs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignCatalogItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_items_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="designs.designcatalog",
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="designs.design"
                    ),
                ),
            ],
            options={
                "db_table": "design_catalog_items",
                "ordering": ["order", "-added_at"],
            },
        ),
        migrations.AddField(
            model_name="designcatalog",
            name="designs",
            field=models.ManyToManyField(
                related_name="catalogs",
                through="designs.DesignCatalogItem",
                to="designs.design",
            ),
        ),
        migrations.CreateModel(
            name="DesignTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("poster", "Poster"),
                            ("banner", "Banner"),
                            ("flyer", "Flyer"),
                            ("business_card", "Business Card"),
                            ("logo", "Logo"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("preview_image", models.ImageField(upload_to="templates/previews/")),
                ("template_file", models.FileField(upload_to="templates/files/")),
                ("is_public", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Template",
                "verbose_name_plural": "Design Templates",
                "db_table": "design_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["organization", "status"], name="designs_organiz_f1be0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["organization", "created_by"], name="designs_organiz_32cb35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["organization", "design_type"],
                name="designs_organiz_30b6ad_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="designcatalogitem",
            unique_together={("catalog", "design")},
        ),
        migrations.AddIndex(
            model_name="designtemplate",
            index=models.Index(
                fields=["organization", "template_type"],
                name="design_temp_organiz_b0d2fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="designtemplate",
            index=models.Index(
                fields=["organization", "is_public"],
                name="design_temp_organiz_2f1684_idx",
            ),
        ),
    ]
