# Generated by Django 5.2.6 on 2025-10-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_services", "0002_scheduledpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiprovider",
            name="name",
            field=models.CharField(
                choices=[
                    ("gemini", "Google Gemini"),
                    ("openai", "OpenAI"),
                    ("stability", "Stability AI"),
                    ("midjourney", "Midjourney"),
                ],
                max_length=100,
            ),
        ),
    ]
