# Generated by Django 5.2.5 on 2025-11-19 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_services", "0004_remove_aigenerationrequest_result_urls_and_more"),
        ("organizations", "0003_alter_organizationinvitation_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedPoster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(help_text="URL of the generated poster image"),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        help_text="Storage path of the image",
                        max_length=500,
                    ),
                ),
                ("caption", models.TextField(help_text="Short caption for the poster")),
                (
                    "full_caption",
                    models.TextField(
                        blank=True, help_text="Full caption with hashtags"
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="Original prompt used to generate the poster"
                    ),
                ),
                (
                    "aspect_ratio",
                    models.CharField(
                        default="1:1",
                        help_text="Aspect ratio of the poster",
                        max_length=20,
                    ),
                ),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "hashtags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of hashtags"
                    ),
                ),
                ("emoji", models.CharField(blank=True, max_length=50)),
                ("call_to_action", models.TextField(blank=True)),
                ("branding_applied", models.BooleanField(default=False)),
                ("logo_added", models.BooleanField(default=False)),
                ("contact_info_added", models.BooleanField(default=False)),
                ("branding_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_posters",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_posters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="ai_services_organiz_5b39b6_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="ai_services_user_id_f5eaeb_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_services_created_8009f4_idx"
                    ),
                ],
            },
        ),
    ]
