# Generated by Django 5.2.5 on 2025-11-19 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_services", "0005_generatedposter"),
        ("organizations", "0003_alter_organizationinvitation_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedBrandingKit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="Original prompt used to generate the branding kit"
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        default="modern",
                        help_text="Style used for generation",
                        max_length=50,
                    ),
                ),
                (
                    "logo_data",
                    models.TextField(blank=True, help_text="Base64 encoded logo image"),
                ),
                (
                    "logo_format",
                    models.CharField(
                        default="png", help_text="Logo image format", max_length=10
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the logo if stored externally",
                        null=True,
                    ),
                ),
                (
                    "color_palette_data",
                    models.TextField(
                        blank=True, help_text="Base64 encoded color palette image"
                    ),
                ),
                (
                    "color_palette_format",
                    models.CharField(
                        default="png",
                        help_text="Color palette image format",
                        max_length=10,
                    ),
                ),
                (
                    "color_palette_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the color palette if stored externally",
                        null=True,
                    ),
                ),
                (
                    "colors",
                    models.JSONField(
                        blank=True, default=list, help_text="List of hex color codes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_branding_kits",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_branding_kits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="ai_services_organiz_03c455_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="ai_services_user_id_0b3839_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_services_created_803356_idx"
                    ),
                ],
            },
        ),
    ]
