# Generated by Django 5.2.5 on 2025-11-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_services", "0006_generatedbrandingkit"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedposter",
            name="public_url",
            field=models.URLField(
                blank=True, help_text="Public Cloudinary URL for sharing", null=True
            ),
        ),
    ]
