# Generated by Django 5.2.5 on 2025-12-31 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_services", "0007_generatedposter_public_url"),
        ("organizations", "0003_alter_organizationinvitation_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PosterTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Template name/title", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Template description"),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="The actual prompt text used for poster generation"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Template thumbnail image",
                        null=True,
                        upload_to="poster_templates/thumbnails/",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="Template category", max_length=100
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, help_text="Template subcategory", max_length=100
                    ),
                ),
                (
                    "audience",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of target audiences (e.g., ['Men', 'Women', 'Kids'])",
                    ),
                ),
                (
                    "offer",
                    models.CharField(
                        blank=True,
                        default="No Offer",
                        help_text="Offer text or 'No Offer'",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether template is active and visible"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Whether template is featured"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_poster_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poster_templates",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"],
                        name="ai_services_organiz_a5ba9d_idx",
                    ),
                    models.Index(
                        fields=["organization", "category"],
                        name="ai_services_organiz_e3f18d_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_featured"],
                        name="ai_services_is_acti_4c30e9_idx",
                    ),
                ],
            },
        ),
    ]
