# Generated by Django 5.2.5 on 2026-01-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_services", "0008_create_poster_template"),
        ("organizations", "0003_alter_organizationinvitation_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postertemplate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="poster_templates",
                to="organizations.organization",
            ),
        ),
    ]
