# Generated by Django 5.2.6 on 2025-10-07 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0003_alter_organizationinvitation_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("design_ids", models.JSONField(default=list)),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("png", "PNG"),
                            ("jpg", "JPG"),
                            ("pdf", "PDF"),
                            ("svg", "SVG"),
                            ("zip", "ZIP"),
                        ],
                        max_length=10,
                    ),
                ),
                ("export_options", models.JSONField(blank=True, default=dict)),
                (
                    "export_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("download_url", models.URLField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Job",
                "verbose_name_plural": "Export Jobs",
                "db_table": "export_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("download_count", models.IntegerField(default=0)),
                ("user_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "export_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="design_export.exportjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export History",
                "verbose_name_plural": "Export Histories",
                "db_table": "export_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Design"),
                            ("batch", "Batch Export"),
                            ("catalog", "Catalog Export"),
                            ("custom", "Custom Layout"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("png", "PNG"),
                            ("jpg", "JPG"),
                            ("pdf", "PDF"),
                            ("svg", "SVG"),
                            ("zip", "ZIP"),
                        ],
                        max_length=10,
                    ),
                ),
                ("export_options", models.JSONField(blank=True, default=dict)),
                ("layout_config", models.JSONField(blank=True, default=dict)),
                ("usage_count", models.IntegerField(default=0)),
                ("is_public", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_export_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Template",
                "verbose_name_plural": "Export Templates",
                "db_table": "export_templates",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["organization", "status"], name="export_jobs_organiz_e48fa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["user", "status"], name="export_jobs_user_id_d4ca06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["created_at"], name="export_jobs_created_af4995_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["expires_at"], name="export_jobs_expires_89b852_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exporttemplate",
            index=models.Index(
                fields=["organization", "template_type"],
                name="export_temp_organiz_aede05_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exporttemplate",
            index=models.Index(
                fields=["is_public", "is_active"], name="export_temp_is_publ_b2a6dd_idx"
            ),
        ),
    ]
