"""
Django settings for frameio_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import logging
import sys
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
# Try loading from root directory first, then from backend directory
root_env = BASE_DIR.parent / '.env'
backend_env = BASE_DIR / '.env'
if root_env.exists():
    load_dotenv(root_env)
elif backend_env.exists():
    load_dotenv(backend_env)
else:
    # Fallback: try loading from current directory
    load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is required")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "whitenoise",
    
    # Third-party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_spectacular",
    
    # Local apps
    "organizations",
    "users", 
    "designs",
    "ai_services",
    "design_export",
    "collaboration",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # AI Services middleware
    "ai_services.middleware.RateLimitMiddleware",
    "ai_services.middleware.AISecurityMiddleware", 
    "ai_services.middleware.AIUsageTrackingMiddleware",
    "organizations.middleware.TenantMiddleware",
]

ROOT_URLCONF = "frameio_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "frameio_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# MySQL configuration (default)
# Only use SQLite if explicitly requested via USE_SQLITE_FALLBACK=True
USE_SQLITE_FALLBACK = os.getenv('USE_SQLITE_FALLBACK', 'False').lower() == 'true'

if USE_SQLITE_FALLBACK:
    # SQLite fallback (only if explicitly requested)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    if DEBUG:
        print("⚠ Using SQLite fallback (USE_SQLITE_FALLBACK=True)")
else:
    # MySQL configuration (default and recommended)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv('DB_NAME', 'frameio_db'),
            "USER": os.getenv('DB_USER', 'root'),
            "PASSWORD": os.getenv('DB_PASSWORD', ''),
            "HOST": os.getenv('DB_HOST', 'localhost'),
            "PORT": os.getenv('DB_PORT', '3306'),
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                "isolation_level": "read committed",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'users.authentication.DevelopmentAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny' if DEBUG else 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'EXCEPTION_HANDLER': 'ai_services.exception_handler.ai_services_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular settings for API documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'Frameio AI Services API',
    'DESCRIPTION': 'Advanced AI capabilities for color intelligence, background synthesis, and usage metering',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'TAGS': [
        {'name': 'AI Services', 'description': 'Core AI generation and analysis services'},
        {'name': 'Fabric Analysis', 'description': 'Fabric color extraction and texture analysis'},
        {'name': 'Background Generation', 'description': 'AI-generated background synthesis'},
        {'name': 'Usage Tracking', 'description': 'Usage quotas and billing management'},
        {'name': 'Color Matching', 'description': 'Smart color matching algorithms'},
    ],
    'EXTENSIONS_INFO': {
        'x-logo': {
            'url': 'https://example.com/logo.png',
            'altText': 'Frameio Logo'
        }
    },
    'CONTACT': {
        'name': 'Frameio API Support',
        'email': 'api-support@frameio.com',
        'url': 'https://frameio.com/support'
    },
    'LICENSE': {
        'name': 'MIT License',
        'url': 'https://opensource.org/licenses/MIT'
    },
    'EXTERNAL_DOCS': {
        'description': 'Frameio Documentation',
        'url': 'https://docs.frameio.com'
    }
}

# CORS settings
# Allow all origins in development for easier testing
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:3001",
        "http://127.0.0.1:3001",
    ]

CORS_ALLOW_CREDENTIALS = True

# Allow custom headers for development
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-dev-user-id',
    'x-dev-org-id',
]

# Allow all methods in development
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Arcjet configuration
ARCJET_KEY = os.getenv('ARCJET_KEY', '')

# AI Services configuration
# NanoBanana has been removed

# Google Gemini configuration
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
GEMINI_MODEL_NAME = os.getenv('GEMINI_MODEL_NAME', 'gemini-2.5-flash-image')

# Validate Gemini configuration
if not GEMINI_API_KEY:
    print("WARNING: GEMINI_API_KEY not configured. AI services will not be available.")
else:
    print("INFO: GEMINI_API_KEY configured")

# Redis configuration
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'frameio',
        'TIMEOUT': 300,  # 5 minutes default timeout
    },
    'ai_results': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'frameio:ai',
        'TIMEOUT': 3600,  # 1 hour for AI results
    }
}

# Celery configuration for background tasks
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Multi-tenancy settings
TENANT_MODEL = 'organizations.Organization'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# File upload settings
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Storage mode configuration
DOMAIN_URL = os.getenv('DOMAIN_URL', '')  # e.g., https://yourdomain.com for production

# Static files settings
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Email configuration
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'startuptsg@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# SMTP connection timeout settings (in seconds)
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))  # 10 seconds timeout

# Use SMTP backend if password is provided, otherwise use console for development
if EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    if DEBUG:
        print(f"INFO: Email configured - Host: {EMAIL_HOST}:{EMAIL_PORT}, User: {EMAIL_HOST_USER}")
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    if DEBUG:
        print("INFO: EMAIL_HOST_PASSWORD not set. Using console email backend for development.")
        print("      Emails will be printed to console instead of being sent.")

# Custom UTF-8 StreamHandler for Windows compatibility
class UTF8StreamHandler(logging.StreamHandler):
    """StreamHandler that uses UTF-8 encoding to handle Unicode characters."""
    def __init__(self, stream=None):
        super().__init__(stream)
        # Reopen stream with UTF-8 encoding if it's sys.stdout or sys.stderr
        if stream is sys.stdout or stream is sys.stderr:
            # On Windows, we need to reconfigure the stream encoding
            if hasattr(stream, 'reconfigure'):
                try:
                    stream.reconfigure(encoding='utf-8', errors='replace')
                except (AttributeError, ValueError):
                    # If reconfigure fails, we'll handle encoding in emit
                    pass
    
    def emit(self, record):
        try:
            msg = self.format(record)
            stream = self.stream
            # Ensure UTF-8 encoding
            if hasattr(stream, 'buffer'):
                # For text streams, write to underlying buffer with UTF-8
                stream.buffer.write(msg.encode('utf-8', errors='replace'))
                stream.buffer.write(self.terminator.encode('utf-8', errors='replace'))
                stream.buffer.flush()
            else:
                # Fallback: try to write directly
                stream.write(msg + self.terminator)
                stream.flush()
        except (UnicodeEncodeError, UnicodeDecodeError):
            # If encoding still fails, replace problematic characters
            try:
                msg = self.format(record)
                # Replace emoji and other problematic Unicode characters
                safe_msg = msg.encode('ascii', errors='replace').decode('ascii')
                stream = self.stream
                if hasattr(stream, 'buffer'):
                    stream.buffer.write(safe_msg.encode('utf-8', errors='replace'))
                    stream.buffer.write(self.terminator.encode('utf-8', errors='replace'))
                    stream.buffer.flush()
                else:
                    stream.write(safe_msg + self.terminator)
                    stream.flush()
            except Exception:
                self.handleError(record)
        except Exception:
            self.handleError(record)

def utf8_console_handler():
    """Factory function to create UTF-8 console handler."""
    return UTF8StreamHandler(sys.stdout)

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',  # Ensure file handler uses UTF-8
        },
        'console': {
            'level': 'DEBUG',
            '()': utf8_console_handler,  # Use custom UTF-8 handler
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'frameio_backend': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# =============================================================================
# ENVIRONMENT VALIDATION
# =============================================================================
def validate_environment():
    """Validate that all required environment variables are set."""
    required_vars = {
        'SECRET_KEY': SECRET_KEY,
    }
    
    missing_vars = []
    for var_name, var_value in required_vars.items():
        if not var_value:
            missing_vars.append(var_name)
    
    if missing_vars:
        error_msg = f"Missing required environment variables: {', '.join(missing_vars)}"
        if DEBUG:
            print(f"WARNING: {error_msg}")
        else:
            raise ValueError(error_msg)
    
    # Optional but recommended variables
    recommended_vars = {
        'GEMINI_API_KEY': GEMINI_API_KEY,
    }
    
    missing_recommended = []
    for var_name, var_value in recommended_vars.items():
        if not var_value:
            missing_recommended.append(var_name)
    
    if missing_recommended and DEBUG:
        print(f"INFO: Optional environment variables not set: {', '.join(missing_recommended)}")
        print("These are recommended for full functionality.")

# =============================================================================
# PRODUCTION SETTINGS
# =============================================================================
# These settings are applied when DEBUG=False
if not DEBUG:
    # Security settings
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000 if SECURE_SSL_REDIRECT else 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True if SECURE_SSL_REDIRECT else False
    SECURE_HSTS_PRELOAD = True if SECURE_SSL_REDIRECT else False
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Trust proxy headers (important for Nginx reverse proxy)
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if SECURE_SSL_REDIRECT else None
    
    # Static files (served by Nginx in production, but collectstatic still needed)
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    
    # Media files
    MEDIA_ROOT = BASE_DIR / 'media'
    
    # CORS - restrict in production
    CORS_ALLOW_ALL_ORIGINS = False
    # Update these with your actual frontend domain
    production_origins = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
    if production_origins and production_origins[0]:
        CORS_ALLOWED_ORIGINS = [origin.strip() for origin in production_origins if origin.strip()]
    else:
        # Fallback: allow IP and common domains
        CORS_ALLOWED_ORIGINS = [
            "http://13.213.53.199",
            "https://13.213.53.199",
        ]
    
    # Logging - more detailed in production
    LOGGING['handlers']['file']['level'] = 'WARNING'
    LOGGING['root']['level'] = 'WARNING'
    
    # Database connection pooling (optional, for better performance)
    DATABASES['default']['CONN_MAX_AGE'] = 600  # 10 minutes

# Run validation
validate_environment()
