# Generated by Django 5.2.5 on 2025-10-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_companyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="facebook_username",
            field=models.CharField(
                blank=True,
                help_text="Facebook username (without @)",
                max_length=100,
                null=True,
            ),
        ),
    ]
