# Generated by Django 5.2.5 on 2025-10-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_email_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="facebook_link",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Company contact email address",
                max_length=254,
                null=True,
            ),
        ),
    ]
