# Generated by Django 5.2.6 on 2025-12-10 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_facebook_link_add_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="clerk_created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="clerk_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="clerk_updated_at",
        ),
    ]
