# Generated by Django 5.2.5 on 2025-12-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_add_password_reset_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user's paid subscription expires. If set and in the future, user has unlimited access.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_plan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("free", "Free"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="free",
                max_length=50,
            ),
        ),
    ]
